<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../FactoryFPT.Domain/FactoryFPT.Domain.csproj" /><ProjectReference Include="../FactoryFPT.Application/FactoryFPT.Application.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20"><PrivateAssets>all</PrivateAssets></PackageReference><PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" /><PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" /></ItemGroup></Project>